language: node_js
node_js:
  - node
services: mongodb
before_script:
  - mongo adonis --eval 'db.createUser({user:"test",pwd:"test",roles:["dbOwner"]});'
sudo: false
install:
  - npm -g install @adonisjs/cli nyc
  - npm install --no-optional
  - cp .env.example .env
  - adonis key:generate --env testing
  # - adonis migration:run --env testing
  # - chmod 777 storage
# script:
  # - npm run lint
  # - npm run test
